# Generated by Django 5.1.2 on 2024-11-27 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_products', '0002_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FatherCategory',
            fields=[
                ('father_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('father_category_name', models.CharField(max_length=30)),
                ('modified_datetime', models.DateTimeField(auto_now_add=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='father_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_category', to='manage_products.fathercategory'),
        ),
    ]
